### ISSUE TITLE
Applying Kernel Patch on Unraid docker

### ISSUE THREAD

**Issue by BamAlex89** [P3R-CO/openrgb-container#3]
Hi there im using unraid with a x570 Asus Strix an some Vengeance Pro RGB Ram, what can i do to let the Docker recognize the RAM? Could I apply the Kernel Patch to Unraid? Is this even possible?

greetings Alex

**Comment by thomaswalther** [comment]
Hi,
this issue is already quite old, but maybe it still helps.
I am using Unraid on an ASRock B550 Phantom Gaming 4 and I'm using it with some Vengeance Pro RGB Rams, too.
On my first tries, the RAM sticks couldn't be detected, only the Corsair Command Pro and the LED channels from the MB were detected.
But now, they are detected and I am not 100% sure what helped.
I am using the P3R-OpenRGB container from the Unraid Apps with the following mapping in the config:
SYS I2C: /sys/bus/i2c/
DEV I2C: /dev/i2c-0/
SYS I2C: /sys/bus/i2c/devices/
Only with that it didn't worked.
Today I gave it another try, because I have overseen something in the description. I ran this in the Unraid console **_before_** starting the container:
```
modprobe i2c-dev
modprobe i2c-piix4
```
I am not sure if both command were neccessary.

**Comment by CaptainASIC** [comment]
With this being a developer level application, it's hard to pinpoint every issue.  That said, most cases are due to needing other I2C channels, or other drivers not mentioned.  you will have to run lm-sensors and i2cdetect on your own system and modify the container environment for your use case.
